name: capotcha
version: 2.1.2+25
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  intl: ^0.17.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.6
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.13
  string_validator: ^0.3.0
  flutter_verification_code: ^1.1.6
  flutter_svg: ^1.1.5
  skeleton_text: ^3.0.0
  dio: ^4.0.6
  sqflite: ^2.1.0
  path_provider: ^2.0.11
  font_awesome_flutter: ^10.2.1
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  bot_toast: ^4.0.3
  firebase_messaging: ^14.0.3
  firebase_core: ^2.1.1
  flutter_screenutil: ^5.5.4
  google_fonts: ^3.0.1
  badges: ^2.0.3
  connectivity_plus: ^2.3.7
  country_pickers: ^2.0.0
  flutter_spinkit: ^5.1.0
  version_check: ^0.2.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  awesome_notifications: ^0.7.1

dev_dependencies:
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  image_path: assets/images/icon.png
  ios: true

flutter:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
  uses-material-design: true
